targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      flutter_gen:
        options:
          output: lib/gen/
          line_length: 80
          assets:
            outputs:
              class_name: PosAssets
              directory_path_enabled: true # <- Add this line.
